const EXERCISES = [
{id:1,title:"Game Vault",icon:"🎮",focus:"Persistencia real",concept:"PostgreSQL · TypeORM · Entity · Repository",resource:"videojuegos",route:"GET /videojuegos",db:"databridge_e01",modify:"Añade el campo genero. Debe existir en la Entity, persistirse en PostgreSQL, viajar en el JSON y mostrarse en cada tarjeta.",mock:"Hollow Knight",mock2:"Metroidvania · Switch",question:"¿Por qué utilizamos Repository en lugar de acceder a PostgreSQL directamente desde Controller?"},
{id:2,title:"CineBox",icon:"🎬",focus:"Leer una colección",concept:"repository.find()",resource:"peliculas",route:"GET /peliculas",db:"databridge_e02",modify:"Añade favorita y represéntala mediante ♡ / ♥. El dato debe proceder de PostgreSQL.",mock:"Interstellar",mock2:"Ciencia ficción · 2014",question:"¿Qué devuelve conceptualmente repository.find()?"},
{id:3,title:"Pet Profile",icon:"🐾",focus:"Leer un registro concreto",concept:"Path Param · búsqueda individual",resource:"mascotas",route:"GET /mascotas/:id",db:"databridge_e03",modify:"Añade nivelEnergia y muéstralo en la ficha.",mock:"Nala",mock2:"Golden Retriever · 4 años",question:"¿De dónde obtiene el Controller el id solicitado?"},
{id:4,title:"Food Spots",icon:"🍜",focus:"Crear datos desde el móvil",concept:"POST · Body · DTO · create() · save()",resource:"restaurantes",route:"POST /restaurantes",db:"databridge_e04",modify:"Añade precioMedio: Entity + DTO + formulario + POST + tarjeta.",mock:"La Trattoria",mock2:"Italiano · Zaragoza",question:"¿Por qué Entity y DTO no representan exactamente la misma responsabilidad?"},
{id:5,title:"Travel Book",icon:"✈️",focus:"Actualizar datos",concept:"PATCH · edición",resource:"viajes",route:"PATCH /viajes/:id",db:"databridge_e05",modify:"Permite editar también la fecha y verifica que permanece después de reiniciar.",mock:"Tokio",mock2:"Japón · RESERVADO",question:"¿Qué diferencia existe entre POST y PATCH?"},
{id:6,title:"My Library",icon:"📚",focus:"Eliminar y sincronizar la interfaz",concept:"DELETE · estado React",resource:"libros",route:"DELETE /libros/:id",db:"databridge_e06",modify:"Añade Marcar como leído utilizando PATCH.",mock:"1984",mock2:"George Orwell · Pendiente",question:"¿Por qué borrar en PostgreSQL no modifica automáticamente el array que React Native ya tiene en memoria?"},
{id:7,title:"Sneaker Vault",icon:"👟",focus:"CRUD completo",concept:"GET · POST · PATCH · DELETE",resource:"sneakers",route:"CRUD /sneakers",db:"databridge_e07",modify:"Añade stock. Si stock = 0, la interfaz debe mostrar AGOTADO.",mock:"Air Max 1",mock2:"Nike · Stock 4",question:"Explica CRUD relacionando cada operación con su método HTTP."},
{id:8,title:"My Playlists",icon:"🎵",focus:"Relacionar datos",concept:"Clave foránea · OneToMany · ManyToOne",resource:"playlists",route:"GET /playlists/:id",db:"databridge_e08",modify:"Permite añadir una canción a una playlist concreta.",mock:"Entrenamiento",mock2:"12 canciones",question:"¿Qué expresa OneToMany en este modelo?"},
{id:9,title:"Event Radar",icon:"🎟️",focus:"Consultar y filtrar",concept:"Query Params · filtros",resource:"eventos",route:"GET /eventos?ciudad=Zaragoza",db:"databridge_e09",modify:"Combina ciudad + categoría en una misma consulta.",mock:"Tech Meetup",mock2:"Zaragoza · Tecnología",question:"¿Por qué puede ser mejor filtrar en la API que descargar siempre todos los registros?"},
{id:10,title:"Wander",icon:"🌍",focus:"Full Stack Challenge",concept:"Integración autónoma",resource:"destinos",route:"CRUD /destinos",db:"databridge_e10",modify:"Añade una mejora propia coherente que afecte realmente al funcionamiento o a los datos.",mock:"Reikiavik",mock2:"Islandia · Prioridad alta",question:"Explica el recorrido completo del dato desde React Native hasta PostgreSQL y de vuelta."}
];